Repository bytedance/xgplayer, pull requests merged in 2024-12, with the labels that each got.

#1679 fix: hls播放mp2音画不同步
  packages/xgplayer-transmuxer/src/mpeg-ts/fixer.js
Labels: codec:mp3

#1656 fix: (xgplayer) 修复打包后 es / lang 文件夹多语言文件缺失的问题
  packages/xgplayer/src/index.js
Labels: i18n

#1678 fix: 🐛 修复Vivo playsinline失败问题
  packages/xgplayer/src/mediaProxy.js
Labels: mobile

#1686 fix: 🐛 修复rotate插件，在video设置maxWidth时，样式计算错误的问题
  packages/xgplayer/src/player.js
Labels: plugin
